version: '3'
services:
  ai.category:
    image: cc1241c03b43
    ports:
      - "10014:10034"
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  ai.sentiment:
    image: 6c06c0231d53
    ports:
      - "10011:10031"
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  ai.ner:
    image: b6395bfa009a
    ports:
      - "10010:10030"
    restart: always
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  tagger.category:
    build: taggers/category_tagger
    restart: always
    depends_on:
      - ai.category

  tagger.sentiment:
    build: taggers/sentiment_tagger
    restart: always
    depends_on:
      - ai.sentiment

  tagger.ner:
    build: taggers/ner_tagger
    restart: always
    depends_on:
      - ai.ner

  tagger.info:
    build: taggers/info_tagger
    restart: always
    depends_on:
      - ai.sentiment
      - ai.category

  data:
    build: data
    restart: always
    ports:
      - "9000:8000"
    networks:
      - mynetwork

  # ui:
  #   image: jahanbin-ui
  #   restart: always
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - mynetwork

networks:
  mynetwork:
    driver: bridge