services:
  ai.category:
    # build: .
    image: cc1241c03b43
    ports:
      - "10014:10034"
    restart: always

  ai.sentiment:
    # build: .
    image: 6c06c0231d53
    ports:
      - "10011:10031"
    restart: always

  ai.ner:
    # build: .
    image: b6395bfa009a
    ports:
      - "10010:10030"
    restart: always

  tagger.category:
    build: taggers/category_tagger
    # image: tagger.category
    restart: always

  tagger.sentiment:
    build: taggers/sentiment_tagger
    # image: tagger.sentiment
    restart: always

  tagger.ner:
    build: taggers/ner_tagger
    # image: tagger.ner
    restart: always

  tagger.info:
    build: taggers/info_tagger
      # image: tagger.info
    restart: always

  data:
    build: data
    # image: data
    restart: always
    ports:
      - "8000:8000"

  ui:
    # build: .
    image: jahanbin-ui
    restart: always
    ports:
      - "3000:3000"

